artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: s3://project-multitask-bucket/data-storage/data.zip # <--- File zip trên S3
  local_data_file: artifacts/data_ingestion/data.zip  # <--- Tên file khi tải về máy
  unzip_dir: artifacts/data_ingestion # <--- Nơi sẽ giải nén ra

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.pt

training_model:
  root_dir: artifacts/training_model
  trained_model_path: artifacts/training_model/trained_model.pt
  data_classification: artifacts/data_ingestion/data/classification_task
  data_segmentation: artifacts/data_ingestion/data/segmentation_task